name: Python Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v4

      - name: Docker поднимаем
        run: docker build -t myapp .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v4

      - name: Docker поднимаем(Опять)
        run: docker build -t myapp .

      - name: Тесты внутри контейнера
        run: docker run --rm myapp

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v4

      - name: Docker поднимаем(Снова)
        run: docker build -t myapp .

      - name: CD процесс (Деплой)
        run: |
          mkdir -p ../staging
          cp -r . ../staging/